# Generated by Django 5.2.6 on 2025-09-16 13:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('jersey premier league', 'Jersey Premier League'), ('jersey laliga', 'Jersey LALIGA'), ('jersey serie a', 'Jersey Serie A'), ('jersey bundesliga', 'Jersey Bundesliga'), ('jersey ligue 1', 'Jersey Ligue 1'), ('jersey timnas indonesia', 'Jersey Timnas Indonesia')], default='jersey premier league', max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
